var FFI = require('ffi')
var ArrayType = require('ref-array')
var Struct = require('ref-struct')
var Union = require('ref-union');
var ref = require('ref')



var voit = exports.voit = ref.types.void
var uint32 = exports.uint32 = ref.types.uint32
var GLenum = exports.GLenum = uint32
var uchar = exports.uchar = ref.types.uchar
var GLboolean = exports.GLboolean = uchar
var GLbitfield = exports.GLbitfield = uint32
var GLvoid = exports.GLvoid = voit
var char = exports.char = ref.types.char
var GLbyte = exports.GLbyte = char
var short = exports.short = ref.types.short
var GLshort = exports.GLshort = short
var int32 = exports.int32 = ref.types.int32
var GLint = exports.GLint = int32
var GLubyte = exports.GLubyte = uchar
var ushort = exports.ushort = ref.types.ushort
var GLushort = exports.GLushort = ushort
var GLuint = exports.GLuint = uint32
var GLsizei = exports.GLsizei = int32
var float = exports.float = ref.types.float
var GLfloat = exports.GLfloat = float
var GLclampf = exports.GLclampf = float
var double = exports.double = ref.types.double
var GLdouble = exports.GLdouble = double
var GLclampd = exports.GLclampd = double
var GLubyte_ptr = exports.GLubyte_ptr = ref.refType(GLubyte)
var GLboolean_ptr = exports.GLboolean_ptr = ref.refType(GLboolean)
var GLdouble_ptr = exports.GLdouble_ptr = ref.refType(GLdouble)
var GLfloat_ptr = exports.GLfloat_ptr = ref.refType(GLfloat)
var GLint_ptr = exports.GLint_ptr = ref.refType(GLint)
var GLvoid_ptr = exports.GLvoid_ptr = ref.refType(GLvoid)
var GLshort_ptr = exports.GLshort_ptr = ref.refType(GLshort)
var GLbyte_ptr = exports.GLbyte_ptr = ref.refType(GLbyte)
var GLuint_ptr = exports.GLuint_ptr = ref.refType(GLuint)
var GLushort_ptr = exports.GLushort_ptr = ref.refType(GLushort)
var GLvoid_ptr_ptr = exports.GLvoid_ptr_ptr = ref.refType(GLvoid_ptr)
var GLclampf_ptr = exports.GLclampf_ptr = ref.refType(GLclampf)
var voit_ptr = exports.voit_ptr = ref.refType(voit)
var PFNGLDRAWRANGEELEMENTSPROC = FFI.Function( voit, [ uint32, uint32, uint32, int32, uint32, voit_ptr, ] )
var PFNGLTEXIMAGE3DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, int32, int32, uint32, uint32, voit_ptr, ] )
var PFNGLTEXSUBIMAGE3DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, int32, int32, int32, uint32, uint32, voit_ptr, ] )
var PFNGLCOPYTEXSUBIMAGE3DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, int32, int32, int32, int32, ] )
var c__F_glLoadTransposeMatrixd_arr = ArrayType(GLdouble, 16)
var c__F_glLoadTransposeMatrixf_arr = ArrayType(GLfloat, 16)
var c__F_glMultTransposeMatrixd_arr = ArrayType(GLdouble, 16)
var c__F_glMultTransposeMatrixf_arr = ArrayType(GLfloat, 16)
var PFNGLACTIVETEXTUREPROC = FFI.Function( voit, [ uint32, ] )
var PFNGLSAMPLECOVERAGEPROC = FFI.Function( voit, [ float, uchar, ] )
var PFNGLCOMPRESSEDTEXIMAGE3DPROC = FFI.Function( voit, [ uint32, int32, uint32, int32, int32, int32, int32, int32, voit_ptr, ] )
var PFNGLCOMPRESSEDTEXIMAGE2DPROC = FFI.Function( voit, [ uint32, int32, uint32, int32, int32, int32, int32, voit_ptr, ] )
var PFNGLCOMPRESSEDTEXIMAGE1DPROC = FFI.Function( voit, [ uint32, int32, uint32, int32, int32, int32, voit_ptr, ] )
var PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, int32, int32, int32, uint32, int32, voit_ptr, ] )
var PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, int32, uint32, int32, voit_ptr, ] )
var PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC = FFI.Function( voit, [ uint32, int32, int32, int32, uint32, int32, voit_ptr, ] )
var PFNGLGETCOMPRESSEDTEXIMAGEPROC = FFI.Function( voit, [ uint32, int32, voit_ptr, ] )
var PFNGLACTIVETEXTUREARBPROC = FFI.Function( voit, [ uint32, ] )
var PFNGLCLIENTACTIVETEXTUREARBPROC = FFI.Function( voit, [ uint32, ] )
var PFNGLMULTITEXCOORD1DARBPROC = FFI.Function( voit, [ uint32, double, ] )
var double_ptr = exports.double_ptr = ref.refType(double)
var PFNGLMULTITEXCOORD1DVARBPROC = FFI.Function( voit, [ uint32, double_ptr, ] )
var PFNGLMULTITEXCOORD1FARBPROC = FFI.Function( voit, [ uint32, float, ] )
var float_ptr = exports.float_ptr = ref.refType(float)
var PFNGLMULTITEXCOORD1FVARBPROC = FFI.Function( voit, [ uint32, float_ptr, ] )
var PFNGLMULTITEXCOORD1IARBPROC = FFI.Function( voit, [ uint32, int32, ] )
var int32_ptr = exports.int32_ptr = ref.refType(int32)
var PFNGLMULTITEXCOORD1IVARBPROC = FFI.Function( voit, [ uint32, int32_ptr, ] )
var PFNGLMULTITEXCOORD1SARBPROC = FFI.Function( voit, [ uint32, short, ] )
var short_ptr = exports.short_ptr = ref.refType(short)
var PFNGLMULTITEXCOORD1SVARBPROC = FFI.Function( voit, [ uint32, short_ptr, ] )
var PFNGLMULTITEXCOORD2DARBPROC = FFI.Function( voit, [ uint32, double, double, ] )
var PFNGLMULTITEXCOORD2DVARBPROC = FFI.Function( voit, [ uint32, double_ptr, ] )
var PFNGLMULTITEXCOORD2FARBPROC = FFI.Function( voit, [ uint32, float, float, ] )
var PFNGLMULTITEXCOORD2FVARBPROC = FFI.Function( voit, [ uint32, float_ptr, ] )
var PFNGLMULTITEXCOORD2IARBPROC = FFI.Function( voit, [ uint32, int32, int32, ] )
var PFNGLMULTITEXCOORD2IVARBPROC = FFI.Function( voit, [ uint32, int32_ptr, ] )
var PFNGLMULTITEXCOORD2SARBPROC = FFI.Function( voit, [ uint32, short, short, ] )
var PFNGLMULTITEXCOORD2SVARBPROC = FFI.Function( voit, [ uint32, short_ptr, ] )
var PFNGLMULTITEXCOORD3DARBPROC = FFI.Function( voit, [ uint32, double, double, double, ] )
var PFNGLMULTITEXCOORD3DVARBPROC = FFI.Function( voit, [ uint32, double_ptr, ] )
var PFNGLMULTITEXCOORD3FARBPROC = FFI.Function( voit, [ uint32, float, float, float, ] )
var PFNGLMULTITEXCOORD3FVARBPROC = FFI.Function( voit, [ uint32, float_ptr, ] )
var PFNGLMULTITEXCOORD3IARBPROC = FFI.Function( voit, [ uint32, int32, int32, int32, ] )
var PFNGLMULTITEXCOORD3IVARBPROC = FFI.Function( voit, [ uint32, int32_ptr, ] )
var PFNGLMULTITEXCOORD3SARBPROC = FFI.Function( voit, [ uint32, short, short, short, ] )
var PFNGLMULTITEXCOORD3SVARBPROC = FFI.Function( voit, [ uint32, short_ptr, ] )
var PFNGLMULTITEXCOORD4DARBPROC = FFI.Function( voit, [ uint32, double, double, double, double, ] )
var PFNGLMULTITEXCOORD4DVARBPROC = FFI.Function( voit, [ uint32, double_ptr, ] )
var PFNGLMULTITEXCOORD4FARBPROC = FFI.Function( voit, [ uint32, float, float, float, float, ] )
var PFNGLMULTITEXCOORD4FVARBPROC = FFI.Function( voit, [ uint32, float_ptr, ] )
var PFNGLMULTITEXCOORD4IARBPROC = FFI.Function( voit, [ uint32, int32, int32, int32, int32, ] )
var PFNGLMULTITEXCOORD4IVARBPROC = FFI.Function( voit, [ uint32, int32_ptr, ] )
var PFNGLMULTITEXCOORD4SARBPROC = FFI.Function( voit, [ uint32, short, short, short, short, ] )
var PFNGLMULTITEXCOORD4SVARBPROC = FFI.Function( voit, [ uint32, short_ptr, ] )
var PFNGLBLENDEQUATIONSEPARATEATIPROC = FFI.Function( voit, [ uint32, uint32, ] )
var GLeglImageOES = exports.GLeglImageOES = voit_ptr
var PFNGLEGLIMAGETARGETTEXTURE2DOESPROC = FFI.Function( voit, [ uint32, voit_ptr, ] )
var PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOESPROC = FFI.Function( voit, [ uint32, voit_ptr, ] )

FFI.Library(__dirname + '/SDL2', {
	glClearIndex: [ voit, [ GLfloat, ] ],
	glClearColor: [ voit, [ GLclampf, GLclampf, GLclampf, GLclampf, ] ],
	glClear: [ voit, [ GLbitfield, ] ],
	glIndexMask: [ voit, [ GLuint, ] ],
	glColorMask: [ voit, [ GLboolean, GLboolean, GLboolean, GLboolean, ] ],
	glAlphaFunc: [ voit, [ GLenum, GLclampf, ] ],
	glBlendFunc: [ voit, [ GLenum, GLenum, ] ],
	glLogicOp: [ voit, [ GLenum, ] ],
	glCullFace: [ voit, [ GLenum, ] ],
	glFrontFace: [ voit, [ GLenum, ] ],
	glPointSize: [ voit, [ GLfloat, ] ],
	glLineWidth: [ voit, [ GLfloat, ] ],
	glLineStipple: [ voit, [ GLint, GLushort, ] ],
	glPolygonMode: [ voit, [ GLenum, GLenum, ] ],
	glPolygonOffset: [ voit, [ GLfloat, GLfloat, ] ],
	glPolygonStipple: [ voit, [ GLubyte_ptr, ] ],
	glGetPolygonStipple: [ voit, [ GLubyte_ptr, ] ],
	glEdgeFlag: [ voit, [ GLboolean, ] ],
	glEdgeFlagv: [ voit, [ GLboolean_ptr, ] ],
	glScissor: [ voit, [ GLint, GLint, GLsizei, GLsizei, ] ],
	glClipPlane: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glGetClipPlane: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glDrawBuffer: [ voit, [ GLenum, ] ],
	glReadBuffer: [ voit, [ GLenum, ] ],
	glEnable: [ voit, [ GLenum, ] ],
	glDisable: [ voit, [ GLenum, ] ],
	glIsEnabled: [ GLboolean, [ GLenum, ] ],
	glEnableClientState: [ voit, [ GLenum, ] ],
	glDisableClientState: [ voit, [ GLenum, ] ],
	glGetBooleanv: [ voit, [ GLenum, GLboolean_ptr, ] ],
	glGetDoublev: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glGetFloatv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glGetIntegerv: [ voit, [ GLenum, GLint_ptr, ] ],
	glPushAttrib: [ voit, [ GLbitfield, ] ],
	glPopAttrib: [ voit, [ ] ],
	glPushClientAttrib: [ voit, [ GLbitfield, ] ],
	glPopClientAttrib: [ voit, [ ] ],
	glRenderMode: [ GLint, [ GLenum, ] ],
	glGetError: [ GLenum, [ ] ],
	glGetString: [ GLubyte_ptr, [ GLenum, ] ],
	glFinish: [ voit, [ ] ],
	glFlush: [ voit, [ ] ],
	glHint: [ voit, [ GLenum, GLenum, ] ],
	glClearDepth: [ voit, [ GLclampd, ] ],
	glDepthFunc: [ voit, [ GLenum, ] ],
	glDepthMask: [ voit, [ GLboolean, ] ],
	glDepthRange: [ voit, [ GLclampd, GLclampd, ] ],
	glClearAccum: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glAccum: [ voit, [ GLenum, GLfloat, ] ],
	glMatrixMode: [ voit, [ GLenum, ] ],
	glOrtho: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glFrustum: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glViewport: [ voit, [ GLint, GLint, GLsizei, GLsizei, ] ],
	glPushMatrix: [ voit, [ ] ],
	glPopMatrix: [ voit, [ ] ],
	glLoadIdentity: [ voit, [ ] ],
	glLoadMatrixd: [ voit, [ GLdouble_ptr, ] ],
	glLoadMatrixf: [ voit, [ GLfloat_ptr, ] ],
	glMultMatrixd: [ voit, [ GLdouble_ptr, ] ],
	glMultMatrixf: [ voit, [ GLfloat_ptr, ] ],
	glRotated: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glRotatef: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glScaled: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glScalef: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glTranslated: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glTranslatef: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glIsList: [ GLboolean, [ GLuint, ] ],
	glDeleteLists: [ voit, [ GLuint, GLsizei, ] ],
	glGenLists: [ GLuint, [ GLsizei, ] ],
	glNewList: [ voit, [ GLuint, GLenum, ] ],
	glEndList: [ voit, [ ] ],
	glCallList: [ voit, [ GLuint, ] ],
	glCallLists: [ voit, [ GLsizei, GLenum, GLvoid_ptr, ] ],
	glListBase: [ voit, [ GLuint, ] ],
	glBegin: [ voit, [ GLenum, ] ],
	glEnd: [ voit, [ ] ],
	glVertex2d: [ voit, [ GLdouble, GLdouble, ] ],
	glVertex2f: [ voit, [ GLfloat, GLfloat, ] ],
	glVertex2i: [ voit, [ GLint, GLint, ] ],
	glVertex2s: [ voit, [ GLshort, GLshort, ] ],
	glVertex3d: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glVertex3f: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glVertex3i: [ voit, [ GLint, GLint, GLint, ] ],
	glVertex3s: [ voit, [ GLshort, GLshort, GLshort, ] ],
	glVertex4d: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glVertex4f: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glVertex4i: [ voit, [ GLint, GLint, GLint, GLint, ] ],
	glVertex4s: [ voit, [ GLshort, GLshort, GLshort, GLshort, ] ],
	glVertex2dv: [ voit, [ GLdouble_ptr, ] ],
	glVertex2fv: [ voit, [ GLfloat_ptr, ] ],
	glVertex2iv: [ voit, [ GLint_ptr, ] ],
	glVertex2sv: [ voit, [ GLshort_ptr, ] ],
	glVertex3dv: [ voit, [ GLdouble_ptr, ] ],
	glVertex3fv: [ voit, [ GLfloat_ptr, ] ],
	glVertex3iv: [ voit, [ GLint_ptr, ] ],
	glVertex3sv: [ voit, [ GLshort_ptr, ] ],
	glVertex4dv: [ voit, [ GLdouble_ptr, ] ],
	glVertex4fv: [ voit, [ GLfloat_ptr, ] ],
	glVertex4iv: [ voit, [ GLint_ptr, ] ],
	glVertex4sv: [ voit, [ GLshort_ptr, ] ],
	glNormal3b: [ voit, [ GLbyte, GLbyte, GLbyte, ] ],
	glNormal3d: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glNormal3f: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glNormal3i: [ voit, [ GLint, GLint, GLint, ] ],
	glNormal3s: [ voit, [ GLshort, GLshort, GLshort, ] ],
	glNormal3bv: [ voit, [ GLbyte_ptr, ] ],
	glNormal3dv: [ voit, [ GLdouble_ptr, ] ],
	glNormal3fv: [ voit, [ GLfloat_ptr, ] ],
	glNormal3iv: [ voit, [ GLint_ptr, ] ],
	glNormal3sv: [ voit, [ GLshort_ptr, ] ],
	glIndexd: [ voit, [ GLdouble, ] ],
	glIndexf: [ voit, [ GLfloat, ] ],
	glIndexi: [ voit, [ GLint, ] ],
	glIndexs: [ voit, [ GLshort, ] ],
	glIndexub: [ voit, [ GLubyte, ] ],
	glIndexdv: [ voit, [ GLdouble_ptr, ] ],
	glIndexfv: [ voit, [ GLfloat_ptr, ] ],
	glIndexiv: [ voit, [ GLint_ptr, ] ],
	glIndexsv: [ voit, [ GLshort_ptr, ] ],
	glIndexubv: [ voit, [ GLubyte_ptr, ] ],
	glColor3b: [ voit, [ GLbyte, GLbyte, GLbyte, ] ],
	glColor3d: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glColor3f: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glColor3i: [ voit, [ GLint, GLint, GLint, ] ],
	glColor3s: [ voit, [ GLshort, GLshort, GLshort, ] ],
	glColor3ub: [ voit, [ GLubyte, GLubyte, GLubyte, ] ],
	glColor3ui: [ voit, [ GLuint, GLuint, GLuint, ] ],
	glColor3us: [ voit, [ GLushort, GLushort, GLushort, ] ],
	glColor4b: [ voit, [ GLbyte, GLbyte, GLbyte, GLbyte, ] ],
	glColor4d: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glColor4f: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glColor4i: [ voit, [ GLint, GLint, GLint, GLint, ] ],
	glColor4s: [ voit, [ GLshort, GLshort, GLshort, GLshort, ] ],
	glColor4ub: [ voit, [ GLubyte, GLubyte, GLubyte, GLubyte, ] ],
	glColor4ui: [ voit, [ GLuint, GLuint, GLuint, GLuint, ] ],
	glColor4us: [ voit, [ GLushort, GLushort, GLushort, GLushort, ] ],
	glColor3bv: [ voit, [ GLbyte_ptr, ] ],
	glColor3dv: [ voit, [ GLdouble_ptr, ] ],
	glColor3fv: [ voit, [ GLfloat_ptr, ] ],
	glColor3iv: [ voit, [ GLint_ptr, ] ],
	glColor3sv: [ voit, [ GLshort_ptr, ] ],
	glColor3ubv: [ voit, [ GLubyte_ptr, ] ],
	glColor3uiv: [ voit, [ GLuint_ptr, ] ],
	glColor3usv: [ voit, [ GLushort_ptr, ] ],
	glColor4bv: [ voit, [ GLbyte_ptr, ] ],
	glColor4dv: [ voit, [ GLdouble_ptr, ] ],
	glColor4fv: [ voit, [ GLfloat_ptr, ] ],
	glColor4iv: [ voit, [ GLint_ptr, ] ],
	glColor4sv: [ voit, [ GLshort_ptr, ] ],
	glColor4ubv: [ voit, [ GLubyte_ptr, ] ],
	glColor4uiv: [ voit, [ GLuint_ptr, ] ],
	glColor4usv: [ voit, [ GLushort_ptr, ] ],
	glTexCoord1d: [ voit, [ GLdouble, ] ],
	glTexCoord1f: [ voit, [ GLfloat, ] ],
	glTexCoord1i: [ voit, [ GLint, ] ],
	glTexCoord1s: [ voit, [ GLshort, ] ],
	glTexCoord2d: [ voit, [ GLdouble, GLdouble, ] ],
	glTexCoord2f: [ voit, [ GLfloat, GLfloat, ] ],
	glTexCoord2i: [ voit, [ GLint, GLint, ] ],
	glTexCoord2s: [ voit, [ GLshort, GLshort, ] ],
	glTexCoord3d: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glTexCoord3f: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glTexCoord3i: [ voit, [ GLint, GLint, GLint, ] ],
	glTexCoord3s: [ voit, [ GLshort, GLshort, GLshort, ] ],
	glTexCoord4d: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glTexCoord4f: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glTexCoord4i: [ voit, [ GLint, GLint, GLint, GLint, ] ],
	glTexCoord4s: [ voit, [ GLshort, GLshort, GLshort, GLshort, ] ],
	glTexCoord1dv: [ voit, [ GLdouble_ptr, ] ],
	glTexCoord1fv: [ voit, [ GLfloat_ptr, ] ],
	glTexCoord1iv: [ voit, [ GLint_ptr, ] ],
	glTexCoord1sv: [ voit, [ GLshort_ptr, ] ],
	glTexCoord2dv: [ voit, [ GLdouble_ptr, ] ],
	glTexCoord2fv: [ voit, [ GLfloat_ptr, ] ],
	glTexCoord2iv: [ voit, [ GLint_ptr, ] ],
	glTexCoord2sv: [ voit, [ GLshort_ptr, ] ],
	glTexCoord3dv: [ voit, [ GLdouble_ptr, ] ],
	glTexCoord3fv: [ voit, [ GLfloat_ptr, ] ],
	glTexCoord3iv: [ voit, [ GLint_ptr, ] ],
	glTexCoord3sv: [ voit, [ GLshort_ptr, ] ],
	glTexCoord4dv: [ voit, [ GLdouble_ptr, ] ],
	glTexCoord4fv: [ voit, [ GLfloat_ptr, ] ],
	glTexCoord4iv: [ voit, [ GLint_ptr, ] ],
	glTexCoord4sv: [ voit, [ GLshort_ptr, ] ],
	glRasterPos2d: [ voit, [ GLdouble, GLdouble, ] ],
	glRasterPos2f: [ voit, [ GLfloat, GLfloat, ] ],
	glRasterPos2i: [ voit, [ GLint, GLint, ] ],
	glRasterPos2s: [ voit, [ GLshort, GLshort, ] ],
	glRasterPos3d: [ voit, [ GLdouble, GLdouble, GLdouble, ] ],
	glRasterPos3f: [ voit, [ GLfloat, GLfloat, GLfloat, ] ],
	glRasterPos3i: [ voit, [ GLint, GLint, GLint, ] ],
	glRasterPos3s: [ voit, [ GLshort, GLshort, GLshort, ] ],
	glRasterPos4d: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glRasterPos4f: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glRasterPos4i: [ voit, [ GLint, GLint, GLint, GLint, ] ],
	glRasterPos4s: [ voit, [ GLshort, GLshort, GLshort, GLshort, ] ],
	glRasterPos2dv: [ voit, [ GLdouble_ptr, ] ],
	glRasterPos2fv: [ voit, [ GLfloat_ptr, ] ],
	glRasterPos2iv: [ voit, [ GLint_ptr, ] ],
	glRasterPos2sv: [ voit, [ GLshort_ptr, ] ],
	glRasterPos3dv: [ voit, [ GLdouble_ptr, ] ],
	glRasterPos3fv: [ voit, [ GLfloat_ptr, ] ],
	glRasterPos3iv: [ voit, [ GLint_ptr, ] ],
	glRasterPos3sv: [ voit, [ GLshort_ptr, ] ],
	glRasterPos4dv: [ voit, [ GLdouble_ptr, ] ],
	glRasterPos4fv: [ voit, [ GLfloat_ptr, ] ],
	glRasterPos4iv: [ voit, [ GLint_ptr, ] ],
	glRasterPos4sv: [ voit, [ GLshort_ptr, ] ],
	glRectd: [ voit, [ GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glRectf: [ voit, [ GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glRecti: [ voit, [ GLint, GLint, GLint, GLint, ] ],
	glRects: [ voit, [ GLshort, GLshort, GLshort, GLshort, ] ],
	glRectdv: [ voit, [ GLdouble_ptr, GLdouble_ptr, ] ],
	glRectfv: [ voit, [ GLfloat_ptr, GLfloat_ptr, ] ],
	glRectiv: [ voit, [ GLint_ptr, GLint_ptr, ] ],
	glRectsv: [ voit, [ GLshort_ptr, GLshort_ptr, ] ],
	glVertexPointer: [ voit, [ GLint, GLenum, GLsizei, GLvoid_ptr, ] ],
	glNormalPointer: [ voit, [ GLenum, GLsizei, GLvoid_ptr, ] ],
	glColorPointer: [ voit, [ GLint, GLenum, GLsizei, GLvoid_ptr, ] ],
	glIndexPointer: [ voit, [ GLenum, GLsizei, GLvoid_ptr, ] ],
	glTexCoordPointer: [ voit, [ GLint, GLenum, GLsizei, GLvoid_ptr, ] ],
	glEdgeFlagPointer: [ voit, [ GLsizei, GLvoid_ptr, ] ],
	glGetPointerv: [ voit, [ GLenum, GLvoid_ptr_ptr, ] ],
	glArrayElement: [ voit, [ GLint, ] ],
	glDrawArrays: [ voit, [ GLenum, GLint, GLsizei, ] ],
	glDrawElements: [ voit, [ GLenum, GLsizei, GLenum, GLvoid_ptr, ] ],
	glInterleavedArrays: [ voit, [ GLenum, GLsizei, GLvoid_ptr, ] ],
	glShadeModel: [ voit, [ GLenum, ] ],
	glLightf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glLighti: [ voit, [ GLenum, GLenum, GLint, ] ],
	glLightfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glLightiv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetLightfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetLightiv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glLightModelf: [ voit, [ GLenum, GLfloat, ] ],
	glLightModeli: [ voit, [ GLenum, GLint, ] ],
	glLightModelfv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glLightModeliv: [ voit, [ GLenum, GLint_ptr, ] ],
	glMaterialf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glMateriali: [ voit, [ GLenum, GLenum, GLint, ] ],
	glMaterialfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glMaterialiv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetMaterialfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetMaterialiv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glColorMaterial: [ voit, [ GLenum, GLenum, ] ],
	glPixelZoom: [ voit, [ GLfloat, GLfloat, ] ],
	glPixelStoref: [ voit, [ GLenum, GLfloat, ] ],
	glPixelStorei: [ voit, [ GLenum, GLint, ] ],
	glPixelTransferf: [ voit, [ GLenum, GLfloat, ] ],
	glPixelTransferi: [ voit, [ GLenum, GLint, ] ],
	glPixelMapfv: [ voit, [ GLenum, GLsizei, GLfloat_ptr, ] ],
	glPixelMapuiv: [ voit, [ GLenum, GLsizei, GLuint_ptr, ] ],
	glPixelMapusv: [ voit, [ GLenum, GLsizei, GLushort_ptr, ] ],
	glGetPixelMapfv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glGetPixelMapuiv: [ voit, [ GLenum, GLuint_ptr, ] ],
	glGetPixelMapusv: [ voit, [ GLenum, GLushort_ptr, ] ],
	glBitmap: [ voit, [ GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, GLubyte_ptr, ] ],
	glReadPixels: [ voit, [ GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glDrawPixels: [ voit, [ GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glCopyPixels: [ voit, [ GLint, GLint, GLsizei, GLsizei, GLenum, ] ],
	glStencilFunc: [ voit, [ GLenum, GLint, GLuint, ] ],
	glStencilMask: [ voit, [ GLuint, ] ],
	glStencilOp: [ voit, [ GLenum, GLenum, GLenum, ] ],
	glClearStencil: [ voit, [ GLint, ] ],
	glTexGend: [ voit, [ GLenum, GLenum, GLdouble, ] ],
	glTexGenf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glTexGeni: [ voit, [ GLenum, GLenum, GLint, ] ],
	glTexGendv: [ voit, [ GLenum, GLenum, GLdouble_ptr, ] ],
	glTexGenfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glTexGeniv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetTexGendv: [ voit, [ GLenum, GLenum, GLdouble_ptr, ] ],
	glGetTexGenfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetTexGeniv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glTexEnvf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glTexEnvi: [ voit, [ GLenum, GLenum, GLint, ] ],
	glTexEnvfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glTexEnviv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetTexEnvfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetTexEnviv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glTexParameterf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glTexParameteri: [ voit, [ GLenum, GLenum, GLint, ] ],
	glTexParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glTexParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetTexParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetTexParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glGetTexLevelParameterfv: [ voit, [ GLenum, GLint, GLenum, GLfloat_ptr, ] ],
	glGetTexLevelParameteriv: [ voit, [ GLenum, GLint, GLenum, GLint_ptr, ] ],
	glTexImage1D: [ voit, [ GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, GLvoid_ptr, ] ],
	glTexImage2D: [ voit, [ GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid_ptr, ] ],
	glGetTexImage: [ voit, [ GLenum, GLint, GLenum, GLenum, GLvoid_ptr, ] ],
	glGenTextures: [ voit, [ GLsizei, GLuint_ptr, ] ],
	glDeleteTextures: [ voit, [ GLsizei, GLuint_ptr, ] ],
	glBindTexture: [ voit, [ GLenum, GLuint, ] ],
	glPrioritizeTextures: [ voit, [ GLsizei, GLuint_ptr, GLclampf_ptr, ] ],
	glAreTexturesResident: [ GLboolean, [ GLsizei, GLuint_ptr, GLboolean_ptr, ] ],
	glIsTexture: [ GLboolean, [ GLuint, ] ],
	glTexSubImage1D: [ voit, [ GLenum, GLint, GLint, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glTexSubImage2D: [ voit, [ GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glCopyTexImage1D: [ voit, [ GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint, ] ],
	glCopyTexImage2D: [ voit, [ GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, ] ],
	glCopyTexSubImage1D: [ voit, [ GLenum, GLint, GLint, GLint, GLint, GLsizei, ] ],
	glCopyTexSubImage2D: [ voit, [ GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, ] ],
	glMap1d: [ voit, [ GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble_ptr, ] ],
	glMap1f: [ voit, [ GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat_ptr, ] ],
	glMap2d: [ voit, [ GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, GLdouble_ptr, ] ],
	glMap2f: [ voit, [ GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, GLfloat_ptr, ] ],
	glGetMapdv: [ voit, [ GLenum, GLenum, GLdouble_ptr, ] ],
	glGetMapfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetMapiv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glEvalCoord1d: [ voit, [ GLdouble, ] ],
	glEvalCoord1f: [ voit, [ GLfloat, ] ],
	glEvalCoord1dv: [ voit, [ GLdouble_ptr, ] ],
	glEvalCoord1fv: [ voit, [ GLfloat_ptr, ] ],
	glEvalCoord2d: [ voit, [ GLdouble, GLdouble, ] ],
	glEvalCoord2f: [ voit, [ GLfloat, GLfloat, ] ],
	glEvalCoord2dv: [ voit, [ GLdouble_ptr, ] ],
	glEvalCoord2fv: [ voit, [ GLfloat_ptr, ] ],
	glMapGrid1d: [ voit, [ GLint, GLdouble, GLdouble, ] ],
	glMapGrid1f: [ voit, [ GLint, GLfloat, GLfloat, ] ],
	glMapGrid2d: [ voit, [ GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble, ] ],
	glMapGrid2f: [ voit, [ GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat, ] ],
	glEvalPoint1: [ voit, [ GLint, ] ],
	glEvalPoint2: [ voit, [ GLint, GLint, ] ],
	glEvalMesh1: [ voit, [ GLenum, GLint, GLint, ] ],
	glEvalMesh2: [ voit, [ GLenum, GLint, GLint, GLint, GLint, ] ],
	glFogf: [ voit, [ GLenum, GLfloat, ] ],
	glFogi: [ voit, [ GLenum, GLint, ] ],
	glFogfv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glFogiv: [ voit, [ GLenum, GLint_ptr, ] ],
	glFeedbackBuffer: [ voit, [ GLsizei, GLenum, GLfloat_ptr, ] ],
	glPassThrough: [ voit, [ GLfloat, ] ],
	glSelectBuffer: [ voit, [ GLsizei, GLuint_ptr, ] ],
	glInitNames: [ voit, [ ] ],
	glLoadName: [ voit, [ GLuint, ] ],
	glPushName: [ voit, [ GLuint, ] ],
	glPopName: [ voit, [ ] ],
	glDrawRangeElements: [ voit, [ GLenum, GLuint, GLuint, GLsizei, GLenum, GLvoid_ptr, ] ],
	glTexImage3D: [ voit, [ GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, GLvoid_ptr, ] ],
	glTexSubImage3D: [ voit, [ GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glCopyTexSubImage3D: [ voit, [ GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, ] ],
	glColorTable: [ voit, [ GLenum, GLenum, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glColorSubTable: [ voit, [ GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glColorTableParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glColorTableParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glCopyColorSubTable: [ voit, [ GLenum, GLsizei, GLint, GLint, GLsizei, ] ],
	glCopyColorTable: [ voit, [ GLenum, GLenum, GLint, GLint, GLsizei, ] ],
	glGetColorTable: [ voit, [ GLenum, GLenum, GLenum, GLvoid_ptr, ] ],
	glGetColorTableParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetColorTableParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glBlendEquation: [ voit, [ GLenum, ] ],
	glBlendColor: [ voit, [ GLclampf, GLclampf, GLclampf, GLclampf, ] ],
	glHistogram: [ voit, [ GLenum, GLsizei, GLenum, GLboolean, ] ],
	glResetHistogram: [ voit, [ GLenum, ] ],
	glGetHistogram: [ voit, [ GLenum, GLboolean, GLenum, GLenum, GLvoid_ptr, ] ],
	glGetHistogramParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetHistogramParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glMinmax: [ voit, [ GLenum, GLenum, GLboolean, ] ],
	glResetMinmax: [ voit, [ GLenum, ] ],
	glGetMinmax: [ voit, [ GLenum, GLboolean, GLenum, GLenum, GLvoid_ptr, ] ],
	glGetMinmaxParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetMinmaxParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glConvolutionFilter1D: [ voit, [ GLenum, GLenum, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glConvolutionFilter2D: [ voit, [ GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, ] ],
	glConvolutionParameterf: [ voit, [ GLenum, GLenum, GLfloat, ] ],
	glConvolutionParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glConvolutionParameteri: [ voit, [ GLenum, GLenum, GLint, ] ],
	glConvolutionParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glCopyConvolutionFilter1D: [ voit, [ GLenum, GLenum, GLint, GLint, GLsizei, ] ],
	glCopyConvolutionFilter2D: [ voit, [ GLenum, GLenum, GLint, GLint, GLsizei, GLsizei, ] ],
	glGetConvolutionFilter: [ voit, [ GLenum, GLenum, GLenum, GLvoid_ptr, ] ],
	glGetConvolutionParameterfv: [ voit, [ GLenum, GLenum, GLfloat_ptr, ] ],
	glGetConvolutionParameteriv: [ voit, [ GLenum, GLenum, GLint_ptr, ] ],
	glSeparableFilter2D: [ voit, [ GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, GLvoid_ptr, GLvoid_ptr, ] ],
	glGetSeparableFilter: [ voit, [ GLenum, GLenum, GLenum, GLvoid_ptr, GLvoid_ptr, GLvoid_ptr, ] ],
	glActiveTexture: [ voit, [ GLenum, ] ],
	glClientActiveTexture: [ voit, [ GLenum, ] ],
	glCompressedTexImage1D: [ voit, [ GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, GLvoid_ptr, ] ],
	glCompressedTexImage2D: [ voit, [ GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, GLvoid_ptr, ] ],
	glCompressedTexImage3D: [ voit, [ GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, GLvoid_ptr, ] ],
	glCompressedTexSubImage1D: [ voit, [ GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, GLvoid_ptr, ] ],
	glCompressedTexSubImage2D: [ voit, [ GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, GLvoid_ptr, ] ],
	glCompressedTexSubImage3D: [ voit, [ GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, GLvoid_ptr, ] ],
	glGetCompressedTexImage: [ voit, [ GLenum, GLint, GLvoid_ptr, ] ],
	glMultiTexCoord1d: [ voit, [ GLenum, GLdouble, ] ],
	glMultiTexCoord1dv: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord1f: [ voit, [ GLenum, GLfloat, ] ],
	glMultiTexCoord1fv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord1i: [ voit, [ GLenum, GLint, ] ],
	glMultiTexCoord1iv: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord1s: [ voit, [ GLenum, GLshort, ] ],
	glMultiTexCoord1sv: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord2d: [ voit, [ GLenum, GLdouble, GLdouble, ] ],
	glMultiTexCoord2dv: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord2f: [ voit, [ GLenum, GLfloat, GLfloat, ] ],
	glMultiTexCoord2fv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord2i: [ voit, [ GLenum, GLint, GLint, ] ],
	glMultiTexCoord2iv: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord2s: [ voit, [ GLenum, GLshort, GLshort, ] ],
	glMultiTexCoord2sv: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord3d: [ voit, [ GLenum, GLdouble, GLdouble, GLdouble, ] ],
	glMultiTexCoord3dv: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord3f: [ voit, [ GLenum, GLfloat, GLfloat, GLfloat, ] ],
	glMultiTexCoord3fv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord3i: [ voit, [ GLenum, GLint, GLint, GLint, ] ],
	glMultiTexCoord3iv: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord3s: [ voit, [ GLenum, GLshort, GLshort, GLshort, ] ],
	glMultiTexCoord3sv: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord4d: [ voit, [ GLenum, GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glMultiTexCoord4dv: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord4f: [ voit, [ GLenum, GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glMultiTexCoord4fv: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord4i: [ voit, [ GLenum, GLint, GLint, GLint, GLint, ] ],
	glMultiTexCoord4iv: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord4s: [ voit, [ GLenum, GLshort, GLshort, GLshort, GLshort, ] ],
	glMultiTexCoord4sv: [ voit, [ GLenum, GLshort_ptr, ] ],
	glLoadTransposeMatrixd: [ voit, [ c__F_glLoadTransposeMatrixd_arr, ] ],
	glLoadTransposeMatrixf: [ voit, [ c__F_glLoadTransposeMatrixf_arr, ] ],
	glMultTransposeMatrixd: [ voit, [ c__F_glMultTransposeMatrixd_arr, ] ],
	glMultTransposeMatrixf: [ voit, [ c__F_glMultTransposeMatrixf_arr, ] ],
	glSampleCoverage: [ voit, [ GLclampf, GLboolean, ] ],
	glActiveTextureARB: [ voit, [ GLenum, ] ],
	glClientActiveTextureARB: [ voit, [ GLenum, ] ],
	glMultiTexCoord1dARB: [ voit, [ GLenum, GLdouble, ] ],
	glMultiTexCoord1dvARB: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord1fARB: [ voit, [ GLenum, GLfloat, ] ],
	glMultiTexCoord1fvARB: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord1iARB: [ voit, [ GLenum, GLint, ] ],
	glMultiTexCoord1ivARB: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord1sARB: [ voit, [ GLenum, GLshort, ] ],
	glMultiTexCoord1svARB: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord2dARB: [ voit, [ GLenum, GLdouble, GLdouble, ] ],
	glMultiTexCoord2dvARB: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord2fARB: [ voit, [ GLenum, GLfloat, GLfloat, ] ],
	glMultiTexCoord2fvARB: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord2iARB: [ voit, [ GLenum, GLint, GLint, ] ],
	glMultiTexCoord2ivARB: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord2sARB: [ voit, [ GLenum, GLshort, GLshort, ] ],
	glMultiTexCoord2svARB: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord3dARB: [ voit, [ GLenum, GLdouble, GLdouble, GLdouble, ] ],
	glMultiTexCoord3dvARB: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord3fARB: [ voit, [ GLenum, GLfloat, GLfloat, GLfloat, ] ],
	glMultiTexCoord3fvARB: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord3iARB: [ voit, [ GLenum, GLint, GLint, GLint, ] ],
	glMultiTexCoord3ivARB: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord3sARB: [ voit, [ GLenum, GLshort, GLshort, GLshort, ] ],
	glMultiTexCoord3svARB: [ voit, [ GLenum, GLshort_ptr, ] ],
	glMultiTexCoord4dARB: [ voit, [ GLenum, GLdouble, GLdouble, GLdouble, GLdouble, ] ],
	glMultiTexCoord4dvARB: [ voit, [ GLenum, GLdouble_ptr, ] ],
	glMultiTexCoord4fARB: [ voit, [ GLenum, GLfloat, GLfloat, GLfloat, GLfloat, ] ],
	glMultiTexCoord4fvARB: [ voit, [ GLenum, GLfloat_ptr, ] ],
	glMultiTexCoord4iARB: [ voit, [ GLenum, GLint, GLint, GLint, GLint, ] ],
	glMultiTexCoord4ivARB: [ voit, [ GLenum, GLint_ptr, ] ],
	glMultiTexCoord4sARB: [ voit, [ GLenum, GLshort, GLshort, GLshort, GLshort, ] ],
	glMultiTexCoord4svARB: [ voit, [ GLenum, GLshort_ptr, ] ],
	glBlendEquationSeparateATI: [ voit, [ GLenum, GLenum, ] ],
}, exports)